name: "Python testing on MacOS (template)"

on:
  workflow_call:
    inputs:
      python-versions:
        required: false
        type: string
        default: '["3.11", "3.12", "3.13"]' 
      test-path:
        required: false
        type: string
        default: "tests/"

jobs:
  build:
    name: macos (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        python-version: ${{ fromJson(inputs.python-versions) }}
    steps:
      - name: Keep alive
        run: |
          while true; do echo "Still running..."; sleep 300; done &
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: test
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict

      # 📌 Pin libboost-python, to avoid not finding libboost_graph.dylib error
      - name: Pin boost version
        run: conda install libboost-python=1.86.0

      - run: conda install python-casacore
      
      - uses: actions/checkout@v4
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[all]"
          
      - name: Test with pytest
        run: pytest ${{ inputs.test-path }}
