name: ipynb Tests

on:
  workflow_call:
    
jobs:
  build:
    name: ipynb (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        activate-environment: test
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        #channels: conda-forge

    - run: | 
        conda config --add channels conda-forge
        conda install -c conda-forge graphviz 

    - uses: actions/checkout@v4

    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        pip install ".[all]" #The magic if not present download fails in ipynb
        pip install graphviz
        pip install holoviews

    - name: Run Jupyter notebooks
      run: |
       ORIGINAL_DIR=$(pwd)
       for notebook in $(find docs -name '*.ipynb'); do
        echo "Running notebook: $notebook"
  
        NOTEBOOK_DIR=$(dirname "$notebook")
        NOTEBOOK_FILE=$(basename "$notebook")

        cd "$NOTEBOOK_DIR"

        jupyter nbconvert --to notebook --execute "$NOTEBOOK_FILE" --output "$NOTEBOOK_FILE" 
        cd "$ORIGINAL_DIR"
       done
